#!/bin/bash
#
# "Build" static html pages by sandwiching the markdown content with the two
# template halves, and save the output to a given page.
# 
# Requires the Markdown Perl script (https://daringfireball.net/markdown) or
# similar implementation to perform this wonderful hack.
#
# USAGE: pagebuilder MARKDOWN_FILE
# Where MARKDOWN_FILE is the page's content.
# Use your shell's redirection (>) to save the file if you desire.
#
# Copyright 2020 Pinguim Investidor. Licensed under the terms and conditions of
# the  GNU GPL v3. See https://gnu.org/licenses for more information.
#

if [[ $# == 0 ]]
then
    echo "Error: missing contents from markdown file."
    echo "Please specify one markdown file to act as content for your page."
    exit 1
fi

if [[ -z $(which markdown) ]]
then
    echo "`markdown` executable not found."
    echo "Please install markdown.pl (https://daringfireball.net/markdown) or equivalent implementation to use this script."
    exit 1
fi

cat template_top.html
markdown "$1"
cat template_footer.html
