#!/bin/bash
#
# "Build" static html pages by sandwiching the markdown content with the two
# template halves, and save the output to a given page.
# 
# Requires the Markdown Perl script (https://daringfireball.net/markdown) or
# similar implementation to perform this wonderful hack. 
# But, yes, a hack indeed. Why aren't you using a CMS, man...
#
# USAGE: just run ./pagebuilder and let it work its magic. It'll look for all
# *.md files in the directory, sandwich their HTML equivalent along the
# templates and save the content as a new .html file, which can be rendered.
#
# Copyright 2020 Pinguim Investidor. Licensed under the terms and conditions of
# the  GNU GPL v3. See https://gnu.org/licenses for more information.
#

if [[ -z $(which markdown) ]]
then
    echo "`markdown` executable not found."
    echo "Please install markdown.pl (https://daringfireball.net/markdown) or equivalent implementation to use this script."
    exit 1
fi

build() {
    cat template_top.html
    markdown "$1"
    cat template_footer.html
}

for page in *.md
do
    build "$page" > ${page/md/html}
    echo "Page ${page/md/html} created."
done
